"""Indexable, server-rendered landing pages — one per dataset.

Why this exists (2026-10-05): every chart lives behind one URL, `/fe/`, with
hash routes (`#data/portal/chart/gold`). Google does not index hash fragments,
so the site had exactly one data URL to rank with, and could not appear for
"giá vàng SJC hôm nay", "lãi suất tiết kiệm", "tỷ giá USD"... GA4 showed the
few organic visitors who did arrive were the most engaged on the site (87%
engagement, 5+ min) — the problem was volume, not fit.

Each page renders the latest figures, a sparkline (inline SVG — no JS, so
crawlers and AI assistants read it) and the recent history table straight
from `fe/data/*.json` at request time. Those files are regenerated by the
box after every crawl, so the pages are as fresh as the charts without any
build step. Nothing here touches the DB.

Rules: state the source and the date of the data on every page; never
describe a number as fresher than its own date; no forecast or advice.
"""

import html
import json
import os
from datetime import date, datetime

from fastapi import APIRouter
from fastapi.responses import HTMLResponse, Response

router = APIRouter(include_in_schema=False)

_DATA = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))), "fe", "data")
SITE = "https://vietdataverse.online"


# ── formatting ────────────────────────────────────────────────────────────────
def _load(name: str):
    with open(os.path.join(_DATA, name), encoding="utf-8") as f:
        return json.load(f)


def _num(x, dec: int = 0) -> str:
    """Vietnamese number format: 1.234.567,89"""
    if x is None:
        return "—"
    s = f"{x:,.{dec}f}"
    return s.replace(",", "X").replace(".", ",").replace("X", ".")


def _pct(x, dec: int = 2) -> str:
    return "—" if x is None else f"{_num(x, dec)}%"


def _vn_date(d: str) -> str:
    """'2026-10-04' → '04/10/2026'; '2026-08' → '08/2026'."""
    parts = d.split("-")
    return "/".join(reversed(parts))


def _fresh(d: str) -> str:
    """'hôm nay' only when the data really is from the last 2 days — a title
    saying 'hôm nay 24/09' on 04/10 is exactly the overclaim the rules forbid."""
    age = date.today().toordinal() - date.fromisoformat(d).toordinal()
    return "hôm nay" if age <= 2 else "mới nhất"


def _signed(x, fmt) -> str:
    if x is None:
        return "—"
    return ("+" if x > 0 else "") + fmt(x)


def _series(dates, values):
    return [(d, v) for d, v in zip(dates, values) if v is not None]


def _value_on_or_before(points, target: str):
    """Latest value dated <= target, for '1 tháng trước' style comparisons."""
    best = None
    for d, v in points:
        if d <= target:
            best = v
        else:
            break
    return best


def _shift(d: str, days: int) -> str:
    return date.fromordinal(date.fromisoformat(d).toordinal() - days).isoformat()


def _sparkline(points, w: int = 640, h: int = 140) -> str:
    vals = [v for _, v in points]
    if len(vals) < 2:
        return ""
    lo, hi = min(vals), max(vals)
    span = (hi - lo) or 1
    n = len(vals) - 1
    pts = " ".join(f"{i * w / n:.1f},{h - 8 - (v - lo) / span * (h - 16):.1f}"
                   for i, v in enumerate(vals))
    first, last = points[0][0], points[-1][0]
    return (f'<figure class="spark"><svg viewBox="0 0 {w} {h}" preserveAspectRatio="none" '
            f'role="img" aria-label="Diễn biến từ {_vn_date(first)} đến {_vn_date(last)}">'
            f'<polyline fill="none" stroke="#2f5fde" stroke-width="2" points="{pts}"/></svg>'
            f'<figcaption>{_vn_date(first)} → {_vn_date(last)} · thấp nhất {{lo}} · cao nhất {{hi}}'
            f'</figcaption></figure>')


# ── page builders: each returns a dict the template renders ──────────────────
def _gold():
    d = _load("gold_SJC_1y.json")["data"]
    sell = _series(d["dates"], d["sell_prices"])
    buy = _series(d["dates"], d["buy_prices"])
    last_d, last_s = sell[-1]
    last_b = buy[-1][1]
    m1 = _value_on_or_before(sell, _shift(last_d, 30))
    y1 = sell[0][1] if sell[0][0] <= _shift(last_d, 330) else None
    tr = lambda v: f"{_num(v / 1e6, 1)} triệu"
    return dict(
        slug="gia-vang-sjc", chart="gold", short="Giá vàng SJC",
        title=f"Giá vàng SJC {_fresh(last_d)} {_vn_date(last_d)} — lịch sử 1 năm",
        h1="Giá vàng miếng SJC",
        desc=(f"Giá vàng SJC ngày {_vn_date(last_d)}: mua {tr(last_b)}, bán {tr(last_s)} "
              f"đồng/lượng. Lịch sử giá 1 năm, tải CSV, API miễn phí."),
        date=last_d, unit="đồng/lượng",
        kpis=[("Giá mua", _num(last_b), "đồng/lượng"),
              ("Giá bán", _num(last_s), "đồng/lượng"),
              ("So với 30 ngày trước", _signed(last_s - m1 if m1 else None, tr), "giá bán"),
              ("So với 1 năm trước", _signed(last_s - y1 if y1 else None, tr), "giá bán")],
        spark=sell, spark_fmt=tr, spark_label="Giá bán 1 năm qua",
        cols=["Ngày", "Mua (đồng/lượng)", "Bán (đồng/lượng)"],
        rows=[[_vn_date(a), _num(b), _num(s)] for (a, b), (_, s) in zip(buy[-30:], sell[-30:])][::-1],
        source=("Giá niêm yết của Công ty Vàng bạc Đá quý Sài Gòn (SJC), đọc từ 24h.com.vn "
                "và giavang.org, đối chiếu chéo hằng giờ trong giờ hành chính."),
        faq=[(f"Giá vàng SJC hôm nay bao nhiêu?",
              f"Ngày {_vn_date(last_d)}, vàng miếng SJC mua vào {_num(last_b)} và bán ra "
              f"{_num(last_s)} đồng/lượng."),
             ("Chênh lệch mua – bán vàng SJC là bao nhiêu?",
              f"Ngày {_vn_date(last_d)}, chênh lệch là {_num(last_s - last_b)} đồng/lượng.")],
    )


def _silver():
    d = _load("silver_1y.json")["data"]
    sell = _series(d["dates"], d["sell_prices"])
    buy = _series(d["dates"], d["buy_prices"])
    last_d, last_s = sell[-1]
    last_b = buy[-1][1]
    m1 = _value_on_or_before(sell, _shift(last_d, 30))
    return dict(
        slug="gia-bac", chart="silver", short="Giá bạc",
        title=f"Giá bạc Phú Quý {_fresh(last_d)} {_vn_date(last_d)} — lịch sử 1 năm",
        h1="Giá bạc Phú Quý",
        desc=(f"Giá bạc Phú Quý ngày {_vn_date(last_d)}: mua {_num(last_b)}, bán {_num(last_s)} "
              f"đồng/lượng. Lịch sử 1 năm, tải CSV, API."),
        date=last_d, unit="đồng/lượng",
        kpis=[("Giá mua", _num(last_b), "đồng/lượng"),
              ("Giá bán", _num(last_s), "đồng/lượng"),
              ("So với 30 ngày trước", _signed(last_s - m1 if m1 else None, _num), "đồng/lượng")],
        spark=sell, spark_fmt=_num, spark_label="Giá bán 1 năm qua",
        cols=["Ngày", "Mua (đồng/lượng)", "Bán (đồng/lượng)"],
        rows=[[_vn_date(a), _num(b), _num(s)] for (a, b), (_, s) in zip(buy[-30:], sell[-30:])][::-1],
        source="Giá niêm yết của Phú Quý, cập nhật hằng giờ trong giờ hành chính.",
        faq=[("Giá bạc hôm nay bao nhiêu?",
              f"Ngày {_vn_date(last_d)}, bạc Phú Quý mua vào {_num(last_b)} và bán ra "
              f"{_num(last_s)} đồng/lượng.")],
    )


def _termdepo():
    d = _load("termdepo_ACB_1y.json")["data"]
    terms = [("term_1m", "1 tháng"), ("term_3m", "3 tháng"), ("term_6m", "6 tháng"),
             ("term_12m", "12 tháng"), ("term_24m", "24 tháng")]
    s12 = _series(d["dates"], d["term_12m"])
    last_d = d["dates"][-1]
    latest = {k: _series(d["dates"], d[k])[-1][1] for k, _ in terms}
    return dict(
        slug="lai-suat-tiet-kiem", chart="termdepo", short="Lãi suất tiết kiệm",
        title=f"Lãi suất tiết kiệm ACB mới nhất {_vn_date(last_d)} — 1 đến 24 tháng",
        h1="Lãi suất tiết kiệm ACB",
        desc=(f"Lãi suất tiết kiệm ACB ngày {_vn_date(last_d)}: 6 tháng {_pct(latest['term_6m'])}, "
              f"12 tháng {_pct(latest['term_12m'])}/năm. Lịch sử theo kỳ hạn, CSV, API."),
        date=last_d, unit="%/năm",
        kpis=[(lbl, _pct(latest[k]), "/năm") for k, lbl in terms],
        spark=s12, spark_fmt=_pct, spark_label="Kỳ hạn 12 tháng",
        cols=["Ngày"] + [lbl for _, lbl in terms],
        rows=[[_vn_date(d["dates"][i])] + [_pct(d[k][i]) for k, _ in terms]
              for i in range(len(d["dates"]) - 1, max(-1, len(d["dates"]) - 31), -1)],
        source=("Biểu lãi suất huy động niêm yết của Ngân hàng TMCP Á Châu (ACB). "
                "Hiện chỉ theo dõi ACB — không phải mức trung bình toàn thị trường."),
        faq=[("Lãi suất tiết kiệm 12 tháng ACB là bao nhiêu?",
              f"Ngày {_vn_date(last_d)}, ACB niêm yết {_pct(latest['term_12m'])}/năm cho kỳ hạn 12 tháng.")],
    )


def _interbank():
    d = _load("sbv_1y.json")["data"]
    on = _series(d["dates"], d["overnight"])
    last_d = d["dates"][-1]
    pick = lambda k: _series(d["dates"], d[k])[-1][1]
    pol = _load("sbv_policy_all.json")["data"]
    last_change = pol.get("last_change") if isinstance(pol, dict) else None
    return dict(
        slug="lai-suat-lien-ngan-hang", chart="interbank", short="Lãi suất liên ngân hàng",
        title=f"Lãi suất liên ngân hàng & lãi suất điều hành NHNN {_vn_date(last_d)}",
        h1="Lãi suất liên ngân hàng và lãi suất điều hành",
        desc=(f"Lãi suất liên ngân hàng qua đêm {_pct(pick('overnight'))} ngày {_vn_date(last_d)}; "
              f"lãi suất tái cấp vốn {_pct(pick('refinancing'))}. Lịch sử, CSV, API."),
        date=last_d, unit="%/năm",
        kpis=[("Qua đêm", _pct(pick("overnight")), "/năm"),
              ("1 tháng", _pct(pick("month_1")), "/năm"),
              ("3 tháng", _pct(pick("month_3")), "/năm"),
              ("Tái cấp vốn", _pct(pick("refinancing")), "/năm"),
              ("Tái chiết khấu", _pct(pick("rediscount")), "/năm")],
        spark=on, spark_fmt=_pct, spark_label="Lãi suất qua đêm",
        cols=["Ngày", "Qua đêm", "1 tháng", "3 tháng"],
        rows=[[_vn_date(d["dates"][i]), _pct(d["overnight"][i]), _pct(d["month_1"][i]),
               _pct(d["month_3"][i])]
              for i in range(len(d["dates"]) - 1, max(-1, len(d["dates"]) - 31), -1)],
        source=("Lãi suất bình quân liên ngân hàng và lãi suất điều hành do Ngân hàng Nhà nước "
                "Việt Nam (sbv.gov.vn) công bố."
                + (f" Lãi suất điều hành không đổi kể từ {_vn_date(last_change)}."
                   if last_change else "")),
        faq=[("Lãi suất tái cấp vốn hiện nay là bao nhiêu?",
              f"Theo số liệu ngày {_vn_date(last_d)}, lãi suất tái cấp vốn là "
              f"{_pct(pick('refinancing'))}/năm.")],
    )


def _fx():
    v = _load("fxrate_VCB_USD_1y.json")["data"]
    s = _load("fxrate_SBV_USD_1y.json")["data"]
    sell = _series(v["dates"], v["sell_rate"])
    buy = _series(v["dates"], v["buy_cash"])
    central = _series(s["dates"], s["usd_vnd_rate"])
    last_d, last_sell = sell[-1]
    return dict(
        slug="ty-gia-usd", chart="fxrate", short="Tỷ giá USD/VND",
        title=f"Tỷ giá USD/VND {_fresh(last_d)} {_vn_date(last_d)} — Vietcombank & tỷ giá trung tâm",
        h1="Tỷ giá USD/VND",
        desc=(f"Tỷ giá USD Vietcombank ngày {_vn_date(last_d)}: mua {_num(buy[-1][1])}, bán "
              f"{_num(last_sell)}; tỷ giá trung tâm NHNN {_num(central[-1][1])}. Lịch sử, CSV, API."),
        date=last_d, unit="VND/USD",
        kpis=[("Vietcombank mua tiền mặt", _num(buy[-1][1]), "VND"),
              ("Vietcombank bán", _num(last_sell), "VND"),
              (f"Tỷ giá trung tâm ({_vn_date(central[-1][0])})", _num(central[-1][1]), "VND")],
        spark=sell, spark_fmt=_num, spark_label="Vietcombank bán ra",
        cols=["Ngày", "VCB mua tiền mặt", "VCB bán"],
        rows=[[_vn_date(a), _num(b), _num(c)] for (a, b), (_, c) in zip(buy[-30:], sell[-30:])][::-1],
        source=("Tỷ giá niêm yết của Vietcombank và tỷ giá trung tâm do Ngân hàng Nhà nước công bố. "
                "Tỷ giá trung tâm không phải giá mua/bán tại ngân hàng."),
        faq=[("Tỷ giá USD hôm nay bao nhiêu?",
              f"Ngày {_vn_date(last_d)}, Vietcombank bán USD ở mức {_num(last_sell)} VND.")],
    )


def _cpi():
    rows = _load("cpi_monthly.json")["data"]
    last = rows[-1]
    pts = [(r["period"] + "-01", r["yoy_pct"]) for r in rows if r["yoy_pct"] is not None]
    return dict(
        slug="cpi-viet-nam", chart="cpi", short="Lạm phát (CPI)",
        title=f"CPI Việt Nam tháng {_vn_date(last['period'])} — lạm phát theo tháng",
        h1="Chỉ số giá tiêu dùng (CPI) Việt Nam",
        desc=(f"CPI tháng {_vn_date(last['period'])} tăng {_pct(last['yoy_pct'])} so với cùng kỳ, "
              f"{_pct(last['mom_pct'])} so với tháng trước. Lịch sử CPI theo tháng, CSV, API."),
        date=last["period"], unit="%",
        kpis=[("So với cùng kỳ năm trước", _pct(last["yoy_pct"]), ""),
              ("So với tháng trước", _pct(last["mom_pct"]), "")],
        spark=pts, spark_fmt=_pct, spark_label="CPI so với cùng kỳ",
        cols=["Tháng", "So với cùng kỳ", "So với tháng trước"],
        rows=[[_vn_date(r["period"]), _pct(r["yoy_pct"]), _pct(r["mom_pct"])] for r in rows[::-1]],
        source="Tổng cục Thống kê / Cục Thống kê (nso.gov.vn), thông cáo kinh tế – xã hội hằng tháng.",
        faq=[("Lạm phát Việt Nam hiện nay là bao nhiêu?",
              f"CPI tháng {_vn_date(last['period'])} tăng {_pct(last['yoy_pct'])} so với cùng kỳ năm trước.")],
    )


def _gdp():
    rows = [r for r in _load("gdp_quarterly.json")["data"] if r["sector"] == "total"]
    last = rows[-1]
    q = lambda r: f"Quý {r['quarter']}/{r['year']}"
    pts = [(f"{r['year']}-{r['quarter'] * 3:02d}-01", r["growth_yoy_pct"])
           for r in rows if r["growth_yoy_pct"] is not None]
    return dict(
        slug="gdp-viet-nam", chart="gdp", short="Tăng trưởng GDP",
        title=f"Tăng trưởng GDP Việt Nam {q(last)} — số liệu theo quý",
        h1="Tăng trưởng GDP Việt Nam theo quý",
        desc=(f"GDP Việt Nam {q(last)} tăng {_pct(last['growth_yoy_pct'])} so với cùng kỳ. "
              f"Lịch sử tăng trưởng theo quý từ 2020, CSV, API."),
        date=f"{last['year']}-{last['quarter'] * 3:02d}", asof=q(last), unit="%",
        kpis=[(f"GDP {q(last)}", _pct(last["growth_yoy_pct"]), "so với cùng kỳ")],
        spark=pts, spark_fmt=_pct, spark_label="Tăng trưởng GDP so với cùng kỳ",
        cols=["Quý", "Tăng trưởng so với cùng kỳ"],
        rows=[[q(r), _pct(r["growth_yoy_pct"])] for r in rows[::-1]],
        source="Tổng cục Thống kê / Cục Thống kê (nso.gov.vn), thông cáo tình hình kinh tế – xã hội quý.",
        faq=[("Tăng trưởng GDP Việt Nam gần nhất là bao nhiêu?",
              f"{q(last)}: {_pct(last['growth_yoy_pct'])} so với cùng kỳ năm trước.")],
    )


def _trade():
    rows = _load("trade_monthly.json")["data"]
    last = rows[-1]
    pts = [(r["period"] + "-01", r["export_billion_usd"]) for r in rows
           if r["export_billion_usd"] is not None]
    bn = lambda v: "—" if v is None else f"{_num(v, 2)} tỷ USD"
    return dict(
        slug="xuat-nhap-khau", chart="trade", short="Xuất nhập khẩu",
        title=f"Kim ngạch xuất nhập khẩu Việt Nam tháng {_vn_date(last['period'])}",
        h1="Kim ngạch xuất nhập khẩu Việt Nam",
        desc=(f"Tháng {_vn_date(last['period'])}: xuất khẩu {bn(last['export_billion_usd'])}, "
              f"nhập khẩu {bn(last['import_billion_usd'])}. Lịch sử theo tháng từ 2020, CSV, API."),
        date=last["period"], unit="tỷ USD",
        kpis=[("Xuất khẩu", bn(last["export_billion_usd"]), _signed(last["yoy_export_pct"], _pct) + " so với cùng kỳ"),
              ("Nhập khẩu", bn(last["import_billion_usd"]), _signed(last["yoy_import_pct"], _pct) + " so với cùng kỳ"),
              ("Cán cân thương mại", bn(last["trade_balance"]), "")],
        spark=pts, spark_fmt=bn, spark_label="Kim ngạch xuất khẩu",
        cols=["Tháng", "Xuất khẩu", "Nhập khẩu", "Cán cân"],
        rows=[[_vn_date(r["period"]), bn(r["export_billion_usd"]), bn(r["import_billion_usd"]),
               bn(r["trade_balance"])] for r in rows[::-1][:36]],
        source="Tổng cục Thống kê / Cục Thống kê (nso.gov.vn), thông cáo kinh tế – xã hội hằng tháng.",
        faq=[("Xuất khẩu Việt Nam tháng gần nhất là bao nhiêu?",
              f"Tháng {_vn_date(last['period'])}: {bn(last['export_billion_usd'])}.")],
    )


PAGES = dict((
    ("gia-vang-sjc", _gold), ("gia-bac", _silver), ("lai-suat-tiet-kiem", _termdepo),
    ("lai-suat-lien-ngan-hang", _interbank), ("ty-gia-usd", _fx),
    ("cpi-viet-nam", _cpi), ("gdp-viet-nam", _gdp), ("xuat-nhap-khau", _trade),
))
# Display names for internal links — static so the nav never depends on a data
# file loading.
NAV = [("gia-vang-sjc", "Giá vàng SJC"), ("gia-bac", "Giá bạc"),
       ("ty-gia-usd", "Tỷ giá USD"), ("lai-suat-tiet-kiem", "Lãi suất tiết kiệm"),
       ("lai-suat-lien-ngan-hang", "Lãi suất liên ngân hàng"), ("cpi-viet-nam", "CPI"),
       ("gdp-viet-nam", "GDP"), ("xuat-nhap-khau", "Xuất nhập khẩu")]


# ── template ─────────────────────────────────────────────────────────────────
_CSS = """
:root{--bg:#f0f4fa;--card:#fff;--ink:#1e2a3a;--muted:#5a6b7a;--faint:#7c8b9c;--line:#e3e9f3;--brand:#2f5fde}
*{box-sizing:border-box}html,body{overflow-x:clip}
body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 Inter,system-ui,-apple-system,Arial,sans-serif}
a{color:var(--brand);text-decoration:none}a:hover{text-decoration:underline}
.top{background:#fff;border-bottom:1px solid var(--line)}
.top-in,.wrap{max-width:1040px;margin:0 auto;padding:0 16px}
.top-in{display:flex;align-items:center;gap:20px;min-height:56px;flex-wrap:wrap}
.brand{font:500 18px Lora,Georgia,serif;color:var(--ink)}
.nav{display:flex;gap:14px;flex-wrap:wrap;font-size:14px}.nav a{color:var(--muted)}.nav a[aria-current]{color:var(--ink);font-weight:600}
h1{font:500 clamp(28px,4vw,40px)/1.2 Lora,Georgia,serif;margin:32px 0 6px}
h2{font:500 22px/1.3 Lora,Georgia,serif;margin:36px 0 12px}
.asof{color:var(--muted);margin:0 0 20px}
.kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}
.kpi{background:var(--card);border-radius:12px;box-shadow:0 0 0 1px var(--line);padding:16px}
.kpi b{display:block;font-size:13px;font-weight:500;color:var(--muted)}
.kpi span{display:block;font:500 24px/1.3 Lora,Georgia,serif;margin-top:4px}
.kpi small{color:var(--faint);font-size:12px}
.spark{background:var(--card);border-radius:12px;box-shadow:0 0 0 1px var(--line);padding:16px;margin:16px 0 0}
.spark svg{width:100%;height:140px;display:block}.spark figcaption{color:var(--faint);font-size:13px;margin-top:6px}
.cta{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0 0}
.btn{display:inline-block;padding:10px 16px;border-radius:10px;font-weight:500;font-size:15px}
.btn.p{background:var(--brand);color:#fff}.btn.s{background:#eaf0fb;color:var(--ink)}
.tbl{overflow-x:auto;background:var(--card);border-radius:12px;box-shadow:0 0 0 1px var(--line)}
table{border-collapse:collapse;width:100%;font-size:14px}
th,td{padding:9px 14px;text-align:right;border-bottom:1px solid var(--line);white-space:nowrap}
th:first-child,td:first-child{text-align:left}th{color:var(--muted);font-weight:500;font-size:13px}
dl dt{font-weight:600;margin-top:12px}dl dd{margin:4px 0 0;color:var(--muted)}
.src{color:var(--muted);font-size:14px}
footer{margin:48px 0 32px;color:var(--faint);font-size:13px}
"""

_GTAG = """<script async src="https://www.googletagmanager.com/gtag/js?id=G-YB3PKHN2E5"></script>
<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','G-YB3PKHN2E5');gtag('config','G-B9BHYSYDES');</script>"""


def _render(p: dict) -> str:
    e = html.escape
    url = f"{SITE}/{p['slug']}"
    vals = [v for _, v in p["spark"]]
    spark = _sparkline(p["spark"])
    if spark:
        spark = spark.replace("{lo}", e(p["spark_fmt"](min(vals)))).replace(
            "{hi}", e(p["spark_fmt"](max(vals))))
    spark_title = f"<h2>{e(p.get('spark_label', 'Diễn biến'))}</h2>" if spark else ""
    asof = p.get("asof") or _vn_date(p["date"])

    ld = [{
        "@context": "https://schema.org", "@type": "Dataset",
        "name": p["h1"], "description": p["desc"], "url": url,
        "creator": {"@type": "Organization", "name": "Viet Dataverse", "url": SITE},
        "isAccessibleForFree": True, "inLanguage": "vi",
        "spatialCoverage": "Việt Nam",
        "temporalCoverage": f"{p['spark'][0][0]}/{p['spark'][-1][0]}" if p["spark"] else None,
        "distribution": [{"@type": "DataDownload", "encodingFormat": "text/csv",
                          "contentUrl": f"{SITE}/fe/#data/portal/chart/{p['chart']}"}],
    }, {
        "@context": "https://schema.org", "@type": "FAQPage",
        "mainEntity": [{"@type": "Question", "name": q,
                        "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in p["faq"]],
    }]

    nav = "".join(
        f'<a href="/{s}"{" aria-current=page" if s == p["slug"] else ""}>{e(n)}</a>'
        for s, n in NAV)
    kpis = "".join(f'<div class="kpi"><b>{e(a)}</b><span>{e(b)}</span><small>{e(c)}</small></div>'
                   for a, b, c in p["kpis"])
    head = "".join(f"<th>{e(c)}</th>" for c in p["cols"])
    body = "".join("<tr>" + "".join(f"<td>{e(str(c))}</td>" for c in r) + "</tr>" for r in p["rows"])
    faq = "".join(f"<dt>{e(q)}</dt><dd>{e(a)}</dd>" for q, a in p["faq"])
    others = " · ".join(f'<a href="/{s}">{e(n)}</a>' for s, n in NAV if s != p["slug"])

    return f"""<!doctype html><html lang="vi"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{e(p['title'])} | Viet Dataverse</title>
<meta name="description" content="{e(p['desc'])}">
<link rel="canonical" href="{url}">
<meta property="og:type" content="website"><meta property="og:url" content="{url}">
<meta property="og:title" content="{e(p['title'])}"><meta property="og:description" content="{e(p['desc'])}">
<meta property="og:image" content="{SITE}/fe/images/og-card.png">
<meta property="og:image:width" content="1200"><meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" type="image/png" sizes="32x32" href="/fe/images/favicon-32x32.png">
<script type="application/ld+json">{json.dumps(ld, ensure_ascii=False)}</script>
{_GTAG}
<style>{_CSS}</style></head><body>
<header class="top"><div class="top-in"><a class="brand" href="/fe/">Viet Dataverse</a>
<nav class="nav" aria-label="Bộ dữ liệu">{nav}</nav></div></header>
<main class="wrap">
<h1>{e(p['h1'])}</h1>
<p class="asof">Số liệu mới nhất: <strong>{e(asof)}</strong> · đơn vị {e(p['unit'])}</p>
<section class="kpis">{kpis}</section>
{spark_title}{spark}
<div class="cta">
<a class="btn p" href="/fe/#data/portal/chart/{p['chart']}">Xem biểu đồ đầy đủ &amp; tải CSV</a>
<a class="btn s" href="/pages/google-sheets.html">Tự cập nhật trong Google Sheets</a>
<a class="btn s" href="/pages/api-docs.html">Lấy qua API</a>
</div>
<h2>Lịch sử gần đây</h2>
<div class="tbl"><table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>
<h2>Câu hỏi thường gặp</h2><dl>{faq}</dl>
<h2>Nguồn dữ liệu</h2><p class="src">{e(p['source'])} Số liệu chỉ để tham khảo, không phải khuyến nghị đầu tư.</p>
<footer>Bộ dữ liệu khác: {others}<br>© {datetime.now().year} Viet Dataverse — dữ liệu kinh tế Việt Nam</footer>
</main></body></html>"""


def _make(slug: str, builder):
    async def _endpoint():
        try:
            page = builder()
        except (OSError, KeyError, IndexError, ValueError, TypeError):
            # A missing/malformed data file must not 500 a page Google is
            # crawling; 503 tells it to come back rather than drop the URL.
            return Response(status_code=503, headers={"Retry-After": "3600"})
        return HTMLResponse(_render(page), headers={"Cache-Control": "public, max-age=900"})
    return _endpoint


for _slug, _builder in PAGES.items():
    router.add_api_route(f"/{_slug}", _make(_slug, _builder), methods=["GET", "HEAD"])
