window.DOCS_I18N_EN = {
  "ad.toc.start": "Getting started",
  "ad.toc.setup": "API setup (4 steps)",
  "ad.toc.samples": "Real-world examples",
  "ad.toc.sheets": "Use with Google Sheets",
  "ad.toc.auth": "Authentication (API key)",
  "ad.toc.quota": "Quota &amp; limits",
  "ad.toc.errors": "Error codes",
  "ad.toc.endpoints": "Endpoints",
  "ad.toc.commodity": "Commodities",
  "ad.toc.rates": "Rates &amp; FX",
  "ad.toc.macro": "Macro",
  "ad.toc.vn30": "VN30 stocks",
  "ad.toc.analysis": "Price volatility risk",
  "ad.toc.news": "Market news",

  "ad.h1": "Vietnam financial data through one simple API",
  "ad.lead": "Gold, silver, CPI, GDP, interest rates, FX, VN30 — all from a single endpoint. Integrate in minutes with Python, JavaScript, or any language that speaks HTTP.",

  "ad.setup.title": "Set up the API in 4 steps",
  "ad.setup.sub": "Follow them top to bottom — after step 4 you'll be pulling real data into your own code.",

  "ad.step1": "\n                    <h3>Sign up &amp; get an API key</h3>\n                    <p>Your API key is the \"key\" that unlocks the data. Every request needs it.</p>\n                    <ul>\n                        <li><a class=\"inline-link login-link\" href=\"#\">Log in</a> and open the <a class=\"inline-link\" href=\"/pages/developer.html\" target=\"_blank\" rel=\"noopener\">Developer page</a> to get a key.</li>\n                        <li>Free accounts get an API key instantly, with a limit of <strong>1,000 requests/month</strong>.</li>\n                        <li>Click <strong>\"Create API key\"</strong> — the full key (~43 characters) appears right away. Click <strong>\"Copy\"</strong> to grab it.</li>\n                    </ul>\n                    <div class=\"callout\">\n                        <span>🔒</span>\n                        <span><strong>Keep your key secret.</strong> Don't commit it to GitHub or share it — every request made with your key counts against your monthly quota.</span>\n                    </div>\n                ",

  "ad.step2": "\n                    <h3>Try it right in your browser (no code needed)</h3>\n                    <p>The fastest way to check your key works: paste this URL into your browser's address bar, replacing <code class=\"kbd\">YOUR_API_KEY</code> with your own key:</p>\n                    <div class=\"code-block\">https://api.vietdataverse.online/api/v1/gold?type=SJC&amp;period=1m&amp;api_key=YOUR_API_KEY</div>\n                    <p>If you see JSON data come back (with <code class=\"kbd\">\"success\": true</code>), your key works. If you see a <code class=\"kbd\">401</code> error, double-check your key on the <a class=\"inline-link dev-link\" href=\"/pages/developer.html\">Developer page</a>.</p>\n                ",

  "ad.step3": "\n                    <h3>Integrate it into your code</h3>\n                    <p>When calling from code, put the key in the <code class=\"kbd\">X-API-Key</code> header instead of the URL (safer). Pick a language:</p>\n                    <div class=\"code-tabs\">\n                        <button class=\"code-tab active\" onclick=\"switchTab(this, 'curl')\">cURL</button>\n                        <button class=\"code-tab\" onclick=\"switchTab(this, 'python')\">Python</button>\n                        <button class=\"code-tab\" onclick=\"switchTab(this, 'js')\">JavaScript</button>\n                    </div>\n                    <div class=\"code-block\" id=\"tab-curl\">curl \"https://api.vietdataverse.online/api/v1/gold?type=SJC&amp;period=1m\" \\\n  -H \"X-API-Key: YOUR_API_KEY\"</div>\n                    <div class=\"code-block\" id=\"tab-python\" style=\"display:none;\"># pip install requests\nimport requests\n\nheaders = {\"X-API-Key\": \"YOUR_API_KEY\"}\nresp = requests.get(\n    \"https://api.vietdataverse.online/api/v1/gold\",\n    params={\"type\": \"SJC\", \"period\": \"1m\"},\n    headers=headers,\n)\ndata = resp.json()        # {\"success\": true, \"count\": 30, \"data\": {...}}\nprint(data[\"count\"], \"days of data\")</div>\n                    <div class=\"code-block\" id=\"tab-js\" style=\"display:none;\">const res = await fetch(\n  \"https://api.vietdataverse.online/api/v1/gold?type=SJC&amp;period=1m\",\n  { headers: { \"X-API-Key\": \"YOUR_API_KEY\" } }\n);\nconst { data } = await res.json();\nconsole.log(data);</div>\n                ",

  "ad.step4": "\n                    <h3>Read the response &amp; check your quota</h3>\n                    <p>Every successful response looks like this:</p>\n                    <div class=\"code-block\">{\n  \"success\": true,\n  \"type\": \"SJC\",\n  \"period\": \"1m\",\n  \"count\": 30,\n  \"data\": { \"dates\": [...], \"buy_prices\": [...], \"sell_prices\": [...] }\n}</div>\n                    <p>Every response includes a header showing how many calls you have left this month: <code class=\"kbd\">X-RateLimit-Remaining</code>. See <a class=\"inline-link\" href=\"#quota\">Quota &amp; limits</a> and <a class=\"inline-link\" href=\"#errors\">Error codes</a> below for details.</p>\n                ",

  "ad.samples.title": "Real-world examples",
  "ad.samples.sub": "Pick the use case that fits — code is ready to copy &amp; run.",

  "ad.faq1": "\n                    <summary style=\"padding:14px 18px;cursor:pointer;font-weight:500;font-size:14px;list-style:none;display:flex;justify-content:space-between;align-items:center;\">\n                        I want to pull SJC gold prices into Python every day\n                        <span style=\"font-size:11px;color:var(--text-tertiary);font-weight:400;\">commodity</span>\n                    </summary>\n                    <div style=\"padding:0 18px 18px;border-top:1px solid var(--border-cream);\">\n                        <p style=\"font-size:13px;color:var(--text-secondary);margin:12px 0 8px;\">Fetch the last 30 days, filter by SJC, load into a DataFrame:</p>\n                        <div class=\"code-block\">import requests, pandas as pd\n\nAPI_KEY = \"YOUR_API_KEY\"\nBASE    = \"https://api.vietdataverse.online/api/v1\"\n\nr = requests.get(f\"{BASE}/gold\",\n    params={\"type\": \"SJC\", \"period\": \"30d\"},\n    headers={\"X-API-Key\": API_KEY})\ndf = pd.DataFrame(r.json()[\"data\"])\ndf[\"period\"] = pd.to_datetime(df[\"period\"])\nprint(df[[\"period\", \"buy_price\", \"sell_price\"]].tail(5))</div>\n                        <p style=\"font-size:12px;color:var(--text-tertiary);\">Endpoint: <code>GET /api/v1/gold</code> · Params: <code>type</code> (SJC | DOJI | BTMC | PNJ), <code>period</code> (30d | 90d | 1y)</p>\n                    </div>\n                ",

  "ad.faq2": "\n                    <summary style=\"padding:14px 18px;cursor:pointer;font-weight:500;font-size:14px;list-style:none;display:flex;justify-content:space-between;align-items:center;\">\n                        I want to track VCB's daily USD/VND rate\n                        <span style=\"font-size:11px;color:var(--text-tertiary);font-weight:400;\">rates</span>\n                    </summary>\n                    <div style=\"padding:0 18px 18px;border-top:1px solid var(--border-cream);\">\n                        <div class=\"code-block\">import requests\n\nr = requests.get(\n    \"https://api.vietdataverse.online/api/v1/sbv-rate\",\n    params={\"bank\": \"VCB\", \"currency\": \"USD\", \"period\": \"30d\"},\n    headers={\"X-API-Key\": \"YOUR_API_KEY\"})\n\nfor row in r.json()[\"data\"][-5:]:\n    print(f\"{row['period']}  buy={row['buy']:,}  sell={row['sell']:,}\")</div>\n                        <p style=\"font-size:12px;color:var(--text-tertiary);\">Endpoint: <code>GET /api/v1/sbv-rate</code> · Params: <code>bank</code> (VCB | SBV), <code>currency</code> (USD | EUR | JPY…)</p>\n                    </div>\n                ",

  "ad.faq3": "\n                    <summary style=\"padding:14px 18px;cursor:pointer;font-weight:500;font-size:14px;list-style:none;display:flex;justify-content:space-between;align-items:center;\">\n                        I want to compare bank deposit rates by term\n                        <span style=\"font-size:11px;color:var(--text-tertiary);font-weight:400;\">rates</span>\n                    </summary>\n                    <div style=\"padding:0 18px 18px;border-top:1px solid var(--border-cream);\">\n                        <div class=\"code-block\">import requests\n\nr = requests.get(\n    \"https://api.vietdataverse.online/api/v1/termdepo\",\n    params={\"period\": \"90d\"},\n    headers={\"X-API-Key\": \"YOUR_API_KEY\"})\n\ndata = r.json()[\"data\"]\nlatest = data[-1]  # most recent row\nprint(f\"ACB — {latest['period']}\")\nprint(f\"  1 month:  {latest.get('term_1m', '-')}%\")\nprint(f\"  6 months: {latest.get('term_6m', '-')}%\")\nprint(f\"  12 months:{latest.get('term_12m', '-')}%\")</div>\n                        <p style=\"font-size:12px;color:var(--text-tertiary);\">Endpoint: <code>GET /api/v1/termdepo</code></p>\n                    </div>\n                ",

  "ad.faq4": "\n                    <summary style=\"padding:14px 18px;cursor:pointer;font-weight:500;font-size:14px;list-style:none;display:flex;justify-content:space-between;align-items:center;\">\n                        I want Vietnam's CPI for an AI agent\n                        <span style=\"font-size:11px;color:var(--text-tertiary);font-weight:400;\">macro</span>\n                    </summary>\n                    <div style=\"padding:0 18px 18px;border-top:1px solid var(--border-cream);\">\n                        <div class=\"code-block\">import requests\n\ndef get_vn_cpi_context(api_key: str) -> str:\n    \"\"\"Return a context string to inject into an AI agent's system prompt.\"\"\"\n    r = requests.get(\n        \"https://api.vietdataverse.online/api/v1/macro/cpi\",\n        params={\"period\": \"1y\"},\n        headers={\"X-API-Key\": api_key})\n    rows = r.json()[\"data\"][-6:]  # last 6 months\n    lines = [f\"- {d['period']}: CPI {d['value']}% YoY\" for d in rows]\n    return \"Vietnam CPI, last 6 months:\\n\" + \"\\n\".join(lines)\n\nprint(get_vn_cpi_context(\"YOUR_API_KEY\"))</div>\n                        <p style=\"font-size:12px;color:var(--text-tertiary);\">Endpoint: <code>GET /api/v1/macro/cpi</code></p>\n                    </div>\n                ",

  "ad.faq5": "\n                    <summary style=\"padding:14px 18px;cursor:pointer;font-weight:500;font-size:14px;list-style:none;display:flex;justify-content:space-between;align-items:center;\">\n                        I want to pull data straight into Excel — no code\n                        <span style=\"font-size:11px;color:var(--text-tertiary);font-weight:400;\">excel add-in</span>\n                    </summary>\n                    <div style=\"padding:0 18px 18px;border-top:1px solid var(--border-cream);\">\n                        <p style=\"font-size:13px;color:var(--text-secondary);margin:12px 0 10px;\">Install the Excel Add-in — pick a dataset, click \"Import into Excel\", done.</p>\n                        <ol style=\"font-size:13px;color:var(--text-secondary);line-height:2;padding-left:18px;margin-bottom:12px;\">\n                            <li>Go to the <a href=\"/pages/account.html\" style=\"color:var(--terracotta)\">Account page</a> → download <strong>manifest.xml</strong></li>\n                            <li>Excel → <strong>Insert → Get Add-ins → Upload My Add-in</strong> → select the file you just downloaded</li>\n                            <li>The \"Viet Dataverse\" panel appears on the right — enter your API key, pick a dataset, click <strong>Import into Excel</strong></li>\n                        </ol>\n                        <p style=\"font-size:12px;color:var(--text-tertiary);\">Supported: Gold · Silver · FX rates · Interest rates · CPI · VN30 OHLCV · Global data</p>\n                    </div>\n                ",

  "ad.sheets.title": "Use the data in Google Sheets",
  "ad.sheets.sub": "No code — pull gold prices straight into a spreadsheet with one formula (more datasets are on the way).",
  "ad.sheets.p": "\n                Google Sheets has an <code class=\"kbd\">IMPORTDATA()</code> function that reads CSV data straight from the API.\n                Since it can't send headers, Viet Dataverse lets you pass the API key right in the URL via the <code class=\"kbd\">api_key</code> parameter:\n            ",
  "ad.sheets.cta": "See the step-by-step Google Sheets guide →",

  "ad.auth.title": "Authentication",
  "ad.auth.sub": "Every request needs an <code style=\"color:var(--text-primary)\">X-API-Key</code> header with a free key created on the Developer page.",
  "ad.auth.p": "\n                Get a free API key on the <a class=\"dev-link\" href=\"/pages/developer.html\" style=\"color:var(--terracotta)\">Developer page</a> after logging in.\n                Keys are tied to your account — don't share yours, or its usage counts against your quota.\n            ",

  "ad.quota.title": "Quota &amp; limits",
  "ad.quota.sub": "Quota resets on the 1st of each month (Asia/Ho_Chi_Minh time). A burst limit protects the system.",
  "ad.quota.plan": "Free account",
  "ad.quota.desc": "requests/month · resets on the 1st",
  "ad.quota.p": "\n                Response headers: <code style=\"color:var(--text-primary)\">X-RateLimit-Limit</code>,\n                <code style=\"color:var(--text-primary)\">X-RateLimit-Remaining</code>,\n                <code style=\"color:var(--text-primary)\">X-RateLimit-Reset</code> (ISO 8601).\n            ",

  "ad.errors.title": "Error codes",
  "ad.errors.table": "\n                <thead><tr><th>HTTP</th><th>Meaning</th><th>What to do</th></tr></thead>\n                <tbody>\n                    <tr><td class=\"error-code error-401\">401</td><td>Invalid or revoked API key</td><td>Check your key on the Developer page</td></tr>\n                    <tr><td class=\"error-code error-429\">429</td><td>Burst or monthly quota exceeded</td><td>See the <code>Retry-After</code> / <code>X-RateLimit-Reset</code> headers</td></tr>\n                    <tr><td class=\"error-code\" style=\"color:var(--text-tertiary)\">500</td><td>Server error</td><td>Try again shortly — contact support if it persists</td></tr>\n                </tbody>\n            "
};
